### PR TITLE
adding intllib and loot mod support

### PR DESCRIPTION
**Pull request by FaceDeer**

### CODE REVIEW

**Comment by kaeza** [comment]
I really appreciate the work, but please learn to use [branches](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) to keep unrelated changes separate. I can fix this if you want.

About the relevant changes, it would be better to make the `[currency]` part fixed and only translate the message. E.g. something like `minetest.log("info", "[Currency] "..S("Craft items loaded!"))`.

**Comment by FaceDeer** [comment]
Sorry, this was an older change I noticed I hadn't sent a pull request for yet. I'll make these chunkier in the future as discussed in the moreores pull request.

**Comment by kaeza** [comment]
Great, thank you! :)

**Comment by sofar** [comment]
Needs rebase!

**Comment by sofar** [comment]
Resolved conflict with UI. Probably needs squashing.

**Comment by sofar** [comment]
@kaeza, @VanessaE if I can get a thumbs up I'll properly apply this as 2 commits.

**Comment by VanessaE** [comment]
Go for it, @sofar, I trust that it works as intended.  :+1:

**Pull request merged**
